test: test

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -48,6 +48,11 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
         run: |
+          if [ -z "$GH_TOKEN" ]; then
+            echo "Error: GH_TOKEN is not set"
+            exit 1
+          fi
+
           git fetch --prune
 
           # Close current release pull requests and delete release branch
@@ -98,7 +103,7 @@ jobs:
       - uses: ./.github/actions/setup-git-bot-user
       - name: Create a release
         env:
-          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN}}
+          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN}}
         run: |
           pnpm install -g conventional-changelog-cli
           version=$(jq -r '.version' package.json)
@@ -124,7 +129,7 @@ jobs:
     steps:
       - name: Set deployment status to "in_progress"
         env:
-          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
         run: gh api repos/${{ github.repository }}/deployments -f state=in_progress
 
       - name: Deploy to server
@@ -134,11 +139,11 @@ jobs:
       - name: Set deployment status to "success"
         if: success()
         env:
-          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
         run: gh api repos/${{ github.repository }}/deployments -f state=success
 
       - name: Set deployment status to "failure"
         if: failure()
         env:
-          GH_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
         run: gh api repos/${{ github.repository }}/deployments -f state=failure
